### ISSUE TITLE
Deployment checklist!

### ISSUE THREAD

**Issue by araedavis** [araedavis/code-blog#19]
- [x] create package.json file / npm install / don't commit node_modules!
- [x] add node modules to .gitignore
- [x] create server.js file 
- [x] create Procfile
- [x] add heroku as remote
- [x] create new heroku app
- [x] set env vars on heroku
- [x] push
- [x] scale dynos
